### ISSUE TITLE
Loan request - error in order of the requests

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#664] opened 2021-11-11 10:13 UTC
ATTENTION: duplicate of: https://github.com/CERNDocumentServer/cds-ils/issues/627

**Describe the bug**
There is an issue with the date order of the pending loan requests

**To Reproduce**

1. A document has been returned and has 2 loan requests on it: 
<img width="1253" alt="Screenshot 2021-11-11 at 11 08 28" src="https://user-images.githubusercontent.com/12181904/141279568-f468036a-2a4b-43ac-b1f2-32ae03a52708.png">
One request is dated "2021/10/05" the other one is dated "2021/09/30".

2. I select the one dated "2021/09/30".
<img width="1248" alt="Screenshot 2021-11-11 at 11 04 35" src="https://user-images.githubusercontent.com/12181904/141279761-32249df5-0a06-4209-b4af-e9778126310b.png">

3. I click on Check-out and I get this error message:
<img width="1038" alt="Screenshot 2021-11-11 at 11 04 50" src="https://user-images.githubusercontent.com/12181904/141279826-36ea7763-9f5a-44af-8a01-a757e61e1aba.png">

4. If I click on "preceding pending loan request", I get on the request dated "2021/10/05", but the oldest request is the one dated "2021/09/30". 
<img width="1253" alt="Screenshot 2021-11-11 at 11 05 20" src="https://user-images.githubusercontent.com/12181904/141280161-17ae305b-abe2-466c-94f5-d63fe38aae72.png">

**Expected behavior**
It seems the system doesn't handle correctly the dates, the oldest date doesn't seem to be recognised.

**Comment by kprzerwa** [comment] 2021-11-12 15:45
duplicate of https://github.com/CERNDocumentServer/cds-ils/issues/627 to be closed together

**Closed** 2021-11-23 15:56 UTC
Labels: bug
