### ISSUE TITLE
Importer Previewer - feedback report

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#557] opened 2021-07-12 09:42 UTC
### General comments

~~The first record is never displayed on the import page (but imported anyway). [BUG]~~
- [x] Blue preview button is not well displayed (Windows/Firefox, Mac/Firefox)
<img width="145" alt="Picture 1" src="https://user-images.githubusercontent.com/12181904/125264286-03ea6780-e304-11eb-99cc-cc345c526324.png">

- [x] #565
- [x] If the XML file is broken, the system should alert immediately and stop the process
- [x] A file with more than 1000 records breaks
<img width="279" alt="Picture 1" src="https://user-images.githubusercontent.com/12181904/125265608-4a8c9180-e305-11eb-8c07-abc7b7163b62.png">

### Preview
- [x] We should display more results on a page (=100)
- [ ] #571
- [x] The preview shows several times the same document [BUG]
- [ ] #563
- [ ] #564

### Import mode
~~Creation/replacement of e-item: the criteria used is the url.description, the internal note should be used instead.~~
- [ ] #572
- [ ] #566
- Could we maybe have a button to choose ‘yes, it is the same, update it’ or ‘no, it is not the same, create a new record’? 
- Otherwise, how could we force the import if not the same but the script keep indicating ‘partial matches’?

### Delete mode
- [ ] #567

### Details per Source

**EBL**

- [x] Adapt the rules, when indicator not known, ignore the indicator, and treat the field as indicated in the mapping
- [x] Remove EBC in the identifier (not added in the existing records)
- [x] Add in the internal note: EBLYYYYMM  (year and month of importation)
- [x] URL description: ebook
- [x] In case an EBL e-item is matched to a SPR e-item, it should be ignored. For the time being, it is added. 

**SPR**
- [x] Adapt the rules, when indicator not known, ignore the indicator, and treat the field as indicated in the mapping
- [x] Add in the internal note: SPRYYYYMM  (year and month of importation)
- [x] URL description: ebook

**SAF**
- [x] Adapt the rules, when indicator not known, ignore the indicator, and treat the field as indicated in the mapping
- [x] Add in the internal note: SAFYYYYMM  (year and month of importation)
- [x] URL description: ebook

**Comment by kprzerwa** [comment] 2021-07-20 13:04
```The first record is never displayed on the import page (but imported anyway). [BUG] ``` cannot reproduce, I checked and the first record displays fine.

**Comment by agentilb** [comment] 2021-07-20 13:45
Example:
- 3 records in a file are submitted (Provider: Springer), see file (xml saved as txt because Github wouldn't let me attach an xml file)
[SpringerNature_Books_MARCXML_20210720_013821.txt](https://github.com/CERNDocumentServer/cds-ils/files/6848731/SpringerNature_Books_MARCXML_20210720_013821.txt)
- Only 2 records visible in the importer: 
<img width="1250" alt="Screenshot 2021-07-20 at 15 39 40" src="https://user-images.githubusercontent.com/12181904/126334821-857cc8d0-ee13-4127-8322-2de607cf8c49.png">
- 3 records imported: 
<img width="649" alt="Screenshot 2021-07-20 at 15 39 53" src="https://user-images.githubusercontent.com/12181904/126334877-e9139c57-244a-4ca2-9491-6911a803e235.png">

**Comment by kprzerwa** [comment] 2021-07-27 08:38
Requested changes implemented or split on smaller tasks, closing

**Closed by kprzerwa** 2021-07-27 08:38 UTC
Labels: bug
