### ISSUE TITLE
Documents missing  image in sandbox environment.

### ISSUE THREAD

**Issue by Pineirin** [CERNDocumentServer/cds-ils#636] opened 2021-10-25 08:37 UTC
Some documents in sandbox environment don't present either the document image or the default image. This problem is present both in the documents list page, in the front-site, and in the document details page.
Examples of this problem are:
https://sandbox-cds-ils.web.cern.ch/literature/35zpk-5wz31
https://sandbox-cds-ils.web.cern.ch/literature/3m4zk-q9036

**Comment by kprzerwa** [comment] 2022-01-17 12:41
caused by invalid indexing, fixed in v1.2.17

**Closed by kprzerwa** 2022-01-17 12:41 UTC
Labels: bug, triage
